### PR TITLE
Re-export googleapi proto definitions for KMS; updated documentation

### PR DESCRIPTION
**Pull request by AmeliasCode**
Hi,

I've updated the documentation a bit to:

1) Properly point to the google-cloud-kms Crates.io page/icon
2) Properly generate links to the documentation of each KMS operation

I've also re-exported the generated proto-types from googleapis for KMS so that folks don't have to look them up in a separate crate. 

Please let me know if there are any changes you would like me to make to this.

Thanks!

### CODE REVIEW

**Comment by AmeliasCode** [comment]
@yoshidan Sorry for missing the cargo format. I've updated it and also fixed a few imports in tests to use the re-exports. 

Thanks!

**Comment by yoshidan** [comment]
Thanks!

**Comment by AmeliasCode** [comment]
Thanks, @yoshidan ! Would it be possible to push to crates.io when you have time? Thanks so much! :)

**Comment by yoshidan** [comment]
@AmeliasCode Now I published new version.

**Pull request merged**
