### PR TITLE
Get range headers when checking the status of the upload

### LINKED ISSUE #257: [CLOUD STORAGE] Add range headers to resumable 308 response
If the resumable session is not complete the 308 response sends out headers that have the information regarding which bytes are still missing. This info is vital for resuming an interrupted upload.

### PR DESCRIPTION
**Pull request by praveenperera**
closes #257

### CODE REVIEW

**Comment by praveenperera** [comment]
I've tested this in my application and it works well

**Comment by yoshidan** [comment]
Could you fix [CI error](https://github.com/yoshidan/google-cloud-rust/actions/runs/9060596412/job/24890617816?pr=258)

**Comment by praveenperera** [comment]
@yoshidan can you run the tests again please

**Comment by praveenperera** [comment]
@yoshidan fixed the doc test

**Comment by yoshidan** [comment]
Thanks! I will fix rest of the doc test.

**Pull request merged**
