### PR TITLE
feat: Subscription seeking and snapshots

### LINKED ISSUE #53: [pubsub] [feature-request] Support seeking subscriptions
Pubsub supports a `subscription.seek` method to seek subscriptions back to a point in time or a saved snapshot. Can `google-cloud-pubsub` support this method to enable recovery mechanisms in applications?

### PR DESCRIPTION
**Pull request by ditsuke**
Implements
- [x] `subscription.seek`
- [x] `subscription.create_snapshot`
- [x] `subscription.delete_snapshot`
- [x] `subscription.get_snapshot`

Closes #53

### CODE REVIEW

**Comment by yoshidan** [comment]
We can now use credentials in CI during PR. 
`common` and `storage` will be successfully tested if we get the `main` branch merged.

**Comment by ditsuke** [comment]
rebased to `main`

**Comment by ditsuke** [comment]
@yoshidan CI doesn't appear to work. Besides that I just added a test for snapshot methods with [9a2f066](https://github.com/yoshidan/google-cloud-rust/pull/56/commits/9a2f06672a69cddedf137719c503318f17595ed1); it's failing with a RPC response
```
Error: status: InvalidArgument, message: "Invalid [snapshots] name: (name=snapshotName)", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

Could use help figuring out what's going wrong.

**Comment by yoshidan** [comment]
For security reasons, I currently have to relabel `safe to` to re-run CI.

> Besides that I just added a test for snapshot methods with [9a2f066](https://github.com/yoshidan/google-cloud-rust/pull/56/commits/9a2f06672a69cddedf137719c503318f17595ed1); it's failing with a RPC response


According to the documentation, the snapshot format should be `projects/{project}/snapshots/{snap}`.
https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1?hl=ja#google.pubsub.v1.CreateSnapshotRequest

**Comment by yoshidan** [comment]
> CI doesn't appear to work.

I found that the main branch source of my repository is always used when CI is executed, so I will fix the CI.

**Comment by yoshidan** [comment]
> I found that the main branch source of my repository is always used when CI is executed, so I will fix the CI.

done.

**Comment by ditsuke** [comment]
> According to the documentation, the snapshot name format should be `projects/{project}/snapshots/{snap}`. [cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1?hl=ja#google.pubsub.v1.CreateSnapshotRequest](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1?hl=ja#google.pubsub.v1.CreateSnapshotRequest)

@yoshidan thanks, that worked! Now we have a new problem: asserting that our snapshot has the labels passed fails. On inspecting I discovered the "Snapshot" resource returned by both the `create_snapshot` and `get_snapshot` methods has an empty `labels`. Any clue what could be causing this. The test for reference: https://github.com/yoshidan/google-cloud-rust/blob/93a1730c1366279aecd5ad7cf7f71e205a4657ce/pubsub/src/subscription.rs#L815-L831

**Comment by yoshidan** [comment]
I could not find any documentation, but it is likely that labels cannot be set via the gRPC API, as the Go implementation does not allow labels to be specified.
https://github.com/googleapis/google-cloud-go/blob/main/pubsub/snapshot.go#L122

**Comment by yoshidan** [comment]
@ditsuke 

It seems to be a Pub/Sub Emulator limitation.  Label was always empty in response from Pub/Sub Emulator.
But when I created a Snapshot for Subscription on a real GCP, I was able to get the label as a response of `SubscriberClient.create_snapshot`.
Since we use a Pub/Sub Emulator on CI, I would prefer not to include assertions of labels in our regression tests.

**Comment by ditsuke** [comment]
> @ditsuke
> 
> It seems to be a Pub/Sub Emulator limitation. Label was always empty in response from Pub/Sub Emulator. But when I created a Snapshot for Subscription on a real GCP, I was able to get the label as a response of `SubscriberClient.create_snapshot`. Since we use a Pub/Sub Emulator on CI, I would prefer not to include assertions of labels in our regression tests.

@yoshidan thanks for investigating! Had my doubts about the emulator too. I'll remove the label assertion for now then.

**Comment by ditsuke** [comment]
Added tests for seek operations and fixed compat with emu. Should be ready to go!

**Comment by ditsuke** [comment]
@yoshidan thanks for merging and apologies for missing fmt again 😅
Could you create a new release in crates.io?

**Comment by yoshidan** [comment]
I will be releasing a new version tonight. I will let you know when it is complete.

**Comment by yoshidan** [comment]
@ditsuke I published 0.7.0
https://crates.io/crates/google-cloud-pubsub

**Pull request merged**
